# -*- coding: utf-8 -*-
"""TEST_SABOTAGE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dm-6s8J4b0xKa2fmyeX-D6HimoiCLXUv
"""

import os
import struct

# The Chaos Monkey: Targets the Primary Map and destroys it.
target_file = "band1.zip" # Change if your file is named differently

with open(target_file, "r+b") as f:
    f.seek(-56, os.SEEK_END) # Go to the dual-pointer footer
    primary_ptr, shadow_ptr, orig_size, m_hash = struct.unpack(">QQQ32s", f.read(56))

    # Seek to the Primary Map and overwrite the first 10 bytes with garbage zeros
    f.seek(primary_ptr)
    f.write(b"\x00" * 10)

print("[SABOTAGE COMPLETE] The Primary Map has been destroyed.")